# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('displayname', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name=b'Email')),
                ('password', models.CharField(max_length=50, verbose_name=b'Password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=400)),
                ('fb_token', models.CharField(blank=True, max_length=400)),
                ('google_token', models.CharField(blank=True, max_length=400)),
                ('linkedin_token', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
