# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniff', '0002_auto_20161102_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fb_token',
            new_name='fb_id',
        ),
    ]
