# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniff', '0005_auto_20161102_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_userId',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
