# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniff', '0006_user_google_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linkedin_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
